openapi: "3.0.1"
info:
  title: "confirm-forgot-password"
  version: "2026-01-24 20:29:49UTC"
servers:
- url: "https://bpkgvv1sdd.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /confirm-forgot-password:
    post:
      responses:
        default:
          description: "Default response for POST /confirm-forgot-password"
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:469695853333:function:confirmForgotPassword/invocations"
        connectionType: "INTERNET"
x-amazon-apigateway-cors:
  allowMethods:
  - "OPTIONS"
  - "POST"
  allowHeaders:
  - "content-type"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
