openapi: "3.0.1"
info:
  title: "getknowledgeapi"
  version: "2026-01-24 20:29:53UTC"
servers:
- url: "https://d60d2iioma.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /chat:
    post:
      responses:
        default:
          description: "Default response for POST /chat"
      security:
      - CognitoToken: []
      x-amazon-apigateway-integration:
        payloadFormatVersion: "2.0"
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:469695853333:function:getKnowledge/invocations"
        connectionType: "INTERNET"
components:
  securitySchemes:
    CognitoToken:
      type: "oauth2"
      flows: {}
      x-amazon-apigateway-authorizer:
        identitySource: "$request.header.Authorization"
        jwtConfiguration:
          audience:
          - "79b4srl7ki07bvdvdnms12ebl6"
          issuer: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_izlMRmzQz"
        type: "jwt"
x-amazon-apigateway-cors:
  allowMethods:
  - "OPTIONS"
  - "POST"
  allowHeaders:
  - "authorization"
  - "content-type"
  maxAge: 0
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"
